/*
 * fuzz_parser.c — libFuzzer harness for the yam parser.
 *
 * Each iteration feeds the fuzzer-generated bytes into yam_parser_new and
 * drains the event stream. Both merge keys and alias resolution are enabled
 * so the harder code paths (anchored maps, sequence merges, alias expansion)
 * are exercised. The arena is recreated per iteration so we don't lose
 * coverage of arena init/teardown.
 *
 * Build (via `just fuzz`):
 *   clang -fsanitize=fuzzer,address,undefined -g -O1 -Iinclude \
 *         fuzz/fuzz_parser.c src/yam_*.c -o build/fuzz_parser
 *
 * Run:
 *   ./build/fuzz_parser -max_total_time=60 \
 *       -artifact_prefix=fuzz/crashes/ fuzz/corpus
 *
 * Crash/oom inputs land under fuzz/crashes/; the corpus grows under
 * fuzz/corpus/ and is gitignored.
 */

#include "yam/yam.h"

#include <stddef.h>
#include <stdint.h>

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    yam_arena *a = yam_arena_new(4096);
    if (!a) return 0;

    yam_parser *p = yam_parser_new((const char *)data, size, a);
    if (!p) { yam_arena_free(a); return 0; }

    /* Exercise the parser's harder code paths. */
    yam_parser_set_merge(p, true);
    yam_parser_set_resolve(p, true);

    yam_event evt;
    int events = 0;
    while (yam_parse_next(p, &evt) == YAM_OK) {
        if (evt.type == YAM_EVT_STREAM_END) break;
        /* Defensive cap — the parser has its own max_events guard, but
         * belt-and-braces here so the fuzzer doesn't spin on inputs that
         * somehow bypass it. */
        if (++events > 100000) break;
    }

    yam_parser_free(p);
    yam_arena_free(a);
    return 0;
}
